vast.py
This is an alternative to #4
Use like this
```
ssh $(vast ssh-url)
```
```
scp src $(vast scp-url)
scp $(vast scp-url) dst
```
=> Add ssh-url and scp-url

vast.py
outputs command results for ls and rm
=> instance command execute

vast.py
=> subaccounts

vast.py
=> show duration in seconds with the show instances command

vast.py
some endpoints were not syntaxed correctly, some were not updated for new params
=> endpoint fixup

make_command_docs.py, vast.py
Improved documentation
fixed create instance id issue
fixed execute command issue
added better parse_env error handling
added get machine report function
=> Assorted changes

vast.py
changing some api endpoints, so change is required here
=> role switchup

vast.py
Basic string additions to help people search better
=> Add cpu_arch filter

vast.py
- fixes [Issue #79](https://github.com/vast-ai/vast-python/issues/79) 
- tested ssh-url on ssh, ssh proxy, jupyter, jupyter direct type instances
=> [Fix Issue #79] off by 1 error when using ssh-url

vast.py
host cancel maint CLI function. Trello Ticket: https://trello.com/c/FW2WsVD4/1417-cli-host-cancel-maint
=> host cancel maint

vast.py
adding commands for basic crud operations on account ssh keys as well as instance ssh keys
=> ssh commands

vast.py
moving from optional to required parameters
=> adding better ssh examples

__init__.py, tests/test_vastai_sdk.py, vastai_base.py, vastai_sdk.py
- Created VastAI class for SDK usage
- Created VastAIBase for helpful IDE type hints and visibility otherwise the dynamically added functions do not get shown in my IDE which is annoying and confusing
- Added some very basic test cases because why not-- would love to have that folder be a space for more comprehensive tests in the future
- Should require little to no work as it imports CLI functions directly so should stay up to date besides the VastAIBase will need updating to stay current although that's not crucial just helpful for usage / maintaining the test cases
- Usage should be something like:
```
from vast import VastAI
vast_sdk = VastAI(api_key=MY_API_KEY)
my_instances_info = vast_sdk.show_instances()
...
```
=> SDK implementation of VastAI

vast.py, vastai_base.py, vastai_sdk.py
- Given relevant gpu/instance type info like number of gpus and gpu name, function performs a search offers and then uses the first result to create an instance with
- Simplifies instance creation by combining search offers & create instance
- Needs to wait for backend webserver code to be deployed before merge
=> Launch Instance function

vast.py
Fixes some things uri found in his automated testing primarily around ssh keys, filters, etc
=> fixes: multiple uri tickets

vast.py, vastai_base.py, vastai_sdk.py
- changed location to be alphabetical
- add geographical options to write out your own country list (not just choose from defined lists of continents)
- add order, limit modularity (before these were just set to defaults that you couldn't change)
- template hash fix (add `help="template hash (**Note**: if you use this field, you can skip launch_args and search_params, as they are automatically inferred from the template)"` and added code logic change to match create__instance logic of
```
if args.template_hash is None:
runtype = get_runtype(args)
if runtype == 1:
return 1
json_blob["runtype"] = runtype
```
Test Plan:
- ran launch instance in CLI a few times and everything looks like it works good
=> fix launch instance for some small things

vastai_sdk.py
- Just updated a couple lines in vastai_sdk.py to import vast.py correctly to the file
=> Should Fix SDK implementation in pypi package

README.md, vast.py
Add CRUD CLI commands to manage user environment variables
=> feat: manage user environment variables from api

vast.py
Add CLI support for hosts to force delete machine
=> add CLI for hosts to force delete machine

vast.py
Changes some of the english prose in the help to be hopefully cleaner
=> Addresses #131 - Verbaige and help formatting

vast.py
This makes sure the key being added looks like a public key so that people don't accidentally add a private key or some random string
=> Fixes #133 - ssh keys should allow for file paths

README.md
Add Pypi package link in readme
=> feat: add pypi readme version breadcrumb

README.md, requirements.txt, vast.py
This should be completely backwards compatible and gracefully degrade on systems without the pip library installed.
=> Fixes #138 adds tab completion

vast.py, vastai_sdk.py
This code gives the wrapped functions valid names, function signatures and google formatted help documentation as extracted from the argparse and docstring objects on the functions
=> Further introspection work for the sdk wrapper

vast.py
=> bring search templates in line with admin cli

README.md, vast_machine_tester.py
Fix the vast_machine_tester for running on verified or deverified machiens.
=> Fixed running machines with unverified or deverified status

vast.py
=> Update vast.py - added ssh keygen

vast.py
Fixed the bug where the jupyter runtype is overridden if the --ssh flag is added. Since jupyter includes the ssh runtypes, it should always take precedence if included.
To fix issues with the open button we have to make sure that non-jupyter instances do not have jupyter-related configs in the PORTAL_CONFIG env variable. This is being done on the endpoint but should also be validated in the CLI. I've tested that it works great.
=> portal_config validation and fixing runtype for instance creation

openapi/yaml/create_template.yaml
- add required name param 
- add max length constraints for body params
Ticket reference
https://vastai.atlassian.net/browse/CLN-1935
=> add required name param to create template

openapi/yaml/combined_api.yaml
forgot to generate combined yaml after this PR 
https://github.com/vast-ai/vast-cli/pull/272
=> regen combined yaml
